name: Deploy to PremiaPlus [Boson Rewards]  Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy-master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to server (Master)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_PRODUCTION }}
          username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
          key: ${{ secrets.PRIVATE_KEY_PRODUCTION }}
          script: |
            cd /home/ubuntu/scripts \
            &&  ./deploy.sh


